import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";

const manrope = Manrope({
  variable: "--font-manrope",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Github Lookup",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} antialiased`}>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
